version: '3.8'

# Magma Orchestrator Docker Compose Template
# This file is used by the deployment script to deploy the orchestrator

services:
  # PostgreSQL Database
  postgresql:
    image: postgres:13
    container_name: magma-postgresql
    environment:
      - POSTGRES_DB=${ORC8R_DB_NAME}
      - POSTGRES_USER=${ORC8R_DB_USER}
      - POSTGRES_PASSWORD=${ORC8R_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORC8R_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Orchestrator Controller
  controller:
    image: magma/controller:latest
    container_name: magma-controller
    depends_on:
      - postgresql
    environment:
      - DATABASE_SOURCE=postgresql://${ORC8R_DB_USER}:${ORC8R_DB_PASSWORD}@postgresql:5432/${ORC8R_DB_NAME}?sslmode=disable
      - SQL_DRIVER=postgres
      - SQL_DIALECT=psql
    volumes:
      - ./certs:/var/opt/magma/certs
      - ./configs:/var/opt/magma/configs
    ports:
      - "9079:9079"
      - "9180:9180"
    restart: unless-stopped

  # Orchestrator Proxy
  proxy:
    image: magma/nginx:latest
    container_name: magma-proxy
    depends_on:
      - controller
    volumes:
      - ./certs:/var/opt/magma/certs
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped

  # Orchestrator Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: magma-prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  # Orchestrator Metrics Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: magma-grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: magma-orc8r